### ISSUE TITLE
SublimeLinter doesn't recognize linters installed with NVM

### ISSUE THREAD

**Issue by wldcordeiro** [SublimeLinter/SublimeLinter3#128]
I have a few linters installed with NVM (jshint, csslint) and Sublime Linter won't recognize them. I've added the path to my settings but according to my console SublimeLinter is still looking in the wrong place.

Here's my SublimeLinter settings. 
https://gist.github.com/ec03df57e48eac45263b

**Comment by ruimarinho** [comment]
From my experience, there is absolutely no problem using `nvm` with SublimeLinter. Here's the no-frills edition for those using `zsh` and `iojs`. Your mileage may vary for other combinations.

* Install `nvm` (I've opted for the homebrew version):

```bash
brew install nvm
```

* Install `iojs`:

```bash
nvm install iojs
nvm use iojs
```

* Make sure your `.zshenv` sets up the environment correctly (snippet sourced from the wonderful prezto framework):

```bash
# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
```
* Load the `nvm` script from `~/.zprofile`. I personally prefer setting the `NVM_DIR` env var to my home dir, but this is entirely optional:

```bash
# Set download dir
export NVM_DIR=~/.nvm

# Load nvm script
if [[ -s $(brew --prefix nvm)/nvm.sh ]]; then
  source $(brew --prefix nvm)/nvm.sh
fi
```
* Install the linter modules you want to have available through SublimeLinter. I've chosen `jshint` and `jscs`. The `-g` arguments makes it a global installation, so the binaries will be available at `~/.nvm/versions/io.js/v1.2.0/bin/` due to my `NVM_DIR` setting.

```bash
npm install -g jshint jscs
```

* Open Sublime Text 3, install `SublimeLinter`, then `SublimeLinter-jshint` and lastly `SublimeLinter-jscs`. That's it! 

* Lint away :)

Hope this helps!

**Comment by vasyan** [comment]
@majimboo It's works great! Thanks.

**Comment by andycaramba** [comment]
It works for me
```json
"paths": {
    "linux": [],
    "osx": [
        # I have installed jshint here
        "/PATH/TO/HOMEDIR/node_modules/.bin/",
        # Without this line a got error
        # SublimeLinter: WARNING: no jshint version could be extracted from:
        # env: node: No such file or directory
        "/PATH/TO/HOMEDIR/.nvm/current/bin/"
    ],
    "windows": []
},
```

**Comment by cvbuelow** [comment]
I was having issues but once I did `nvm alias default v0.12.1` all was good

**Comment by chrisl8** [comment]
I solved this problem by adding the following:
```
export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh"  ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
nvm use stable
```
to `~/.bash_profile`
as explained here:
http://www.sublimelinter.com/en/latest/troubleshooting.html#adjusting-shell-startup-files

I think the problem is solved by the documentation, but I hope my comment will help others who find their way here via web search.

**Comment by chauthai** [comment]
@chrisl8 thanks for your help! 
It seems Sublime Text defaults to the bash shell on MacOSX even if you set zsh as your default shell in Terminal.
Your solution finally enable my eslint!

**Comment by arxpoetica** [comment]
Fixed my problem too. Thx.

**Comment by thymikee** [comment]
Anyone having problems with @chrisl8 answer not working on OSX:
1) If you use `zsh` paste this `export NVM_DIR="${HOME}/.nvm"` into `~/.zprofile` (create if not present)
2) `Cmd+Shift+P`, search for `SublimeLinter: Clear Caches` and **clear the cache**.

**Comment by ambodi** [comment]
@aparajita Why not supported? Isn't it as simple as what [HTML Prettify](https://github.com/victorporof/Sublime-HTMLPrettify) guys did by introducing a way to have a config saying where node is installed if its not installed already?

**Comment by grotewold** [comment]
Not saying it can't be done, just saying it isn't currently. If it seems simple, please feel free to contribute! Thanks!

**Comment by btmurrell** [comment]
@borestad, thanks for the pointer to **[n](https://github.com/tj/n)** this kicks ass over nvm, and as advertised works seamlessly with sublime.

**Comment by leomeloxp** [comment]
Did what @thymikee suggested and it fixed it for me. I guess it makes sense that sublime doesn't look at zshrc or bashrc, since at least on linux only .*profile gets read when you log in and startx.

**Comment by yrodriguezo** [comment]
You are such a pussy, if you open Sublime Text from terminal with `subl .` the console inheritance everything. EVERYTHING about paths.

_Go home, you are drunk._

**Comment by grotewold** [comment]
@yrodriguezo, Please watch your language, that is not appropriate behavior.

**Comment by jawshooah** [comment]
@yrodriguezo That kind of language is not welcome here, and your comment is incoherent besides. Please leave.

**Comment by wldcordeiro** [comment]
So since people have posted workarounds I'm closing the issue.

**Comment by vogelino** [comment]
@chrisl8 Mine too! Thx! 
> With :heart: with two years delay!

**Comment by nodkrot** [comment]
Here is what I did (sort of the combination):
In your `~/.zprofile`

```
#
#  NVM
#

export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh"  ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

**Comment by lvl99** [comment]
I saw that there was a point on the [SublimeLinter-jshint](https://github.com/SublimeLinter/SublimeLinter-jshint) page:
> If you are using nvm and zsh, ensure that the line to load nvm is in .zshenv and not .zshrc.

I then added my nvm initialiser shell script (the line above which @nodkrot has above) into the `.zshenv` file, cleared SublimeLinter's cache and restarted Sublime 3. I had SublimeLinter's debug mode on and it was able to locate node via nvm in the path with no errors locating my all my linter plugins too.

**Comment by sqren** [comment]
This is how I solved it:

Open "SublimeLinter Settings" and add:
```
"paths": {
    "linux": [],
    "osx": ["~/.nvm/versions/node/v4.5.0/bin"],
    "windows": []
},
```

And remember to [read the readme](http://sublimelinter.readthedocs.io/en/latest/usage.html#how-linter-executables-are-located) :)

**Comment by AlexyL** [comment]
Thanks @sqren, your solution worked instantly.

_(Of course, Linux users should move the path to the appropriate key)_

**Comment by newhouse** [comment]
For me, like @nodkrot , the problem was that I was using NVM _and_ ZSH. In fact, I'm using Oh My Zsh as well.
I simply had to move the NVM stuff from `.zshrc` to `.zprofiile` and it was fine. This is because `.zshrc` isn't loaded by the shell that Sublime uses I guess.

By the way, this was also staring me in the face in the [`SublimeLinter-eslint` docs](https://github.com/roadhump/SublimeLinter-eslint):

"If you are using nvm and zsh, ensure that the line to load nvm is in `.zprofile` and not `.zshrc.`"

This problem was, I believe, also exacerbated by the fact that I had no "system" installation of Node...otherwise this would have presented itself differently, or not at all.

**Comment by flyskywhy** [comment]
with version 4.0.5, paths eg `"linux":["~/.nvm/v0.11.0/bin/node"]` can't work anymore, I have to

    sudo ln -s ~/.nvm/v0.11.0/bin/node /usr/bin/node

**Comment by kaste** [comment]
I thought that this is documented in the README, but it isn't. Happy to take documentation PRs.

Here is some info for the new SL4

https://github.com/SublimeLinter/SublimeLinter-eslint/blob/4ecc891b6162e242b2d91a6c435e7ec68e29036a/messages/4.0.1.txt#L24-L36

**Comment by elmigranto** [comment]
Worked for me:

  - open your shell with `PATH` set as you want it;
   (pointing to correct `node`, etc.);
 - execute `subl`
    (which is cli command to launch Sublime Text);
 - ...
 - PROFIT!!1.!!!

**Comment by jshado1** [comment]
This sounds like it could be caused by SublimeTextIssues/Core#1877

**Comment by brainthinks** [comment]
@kaste - thank you!  Here is how I got my n installation to work:

```
"linters": {
  "eslint": {
    "disable": false,
    "args": [],
    "excludes": [],
    "env": {
      "PATH": "/home/user/n/bin:$PATH"
    }
  }
}
```

I got the path to my n node executable by running:

`which node`

**Comment by theSekyi** [comment]
@brainthinks what does $PATH do? Do I add it to the end of my `which node` output?

**Comment by maxmckenzie** [comment]
I do not think it is a good idea. as most comments here suggest to add `"osx": ["~/.nvm/versions/node/v4.5.0/bin"],` to your sublime lint conf

note the hardcoded version of node that is referenced `node/v4.5.0`

maybe you're just working on a single app. Maybe your only using one version of node for all you developer needs.

but as this is related with nvm one assumes there are multiple versions of node in play.

on linux you just reference .nvm in your home folder `"linux": ["/home/xam/.nvm"],`

Rather than running eslint against a specific version of node each time as is the case with the above.

**Comment by rreckonerr** [comment]
Had the same problem running Linux Mint 18.3 and node installed with nvm.
First problem I got was `SublimeLinter: WARNING: jshint cannot locate 'jshint'`. To fix it add 
```
    "paths": {
        "linux": [
            "~/.nvm/versions/node/v8.11.1/bin",
        ],
        "osx": [],
        "windows": []
    },
```
to your `~/.config/sublime-text-3/Packages/User/SublimeLinter.sublime-settings` or `Preferences > Package Settings > SublimeLinter > Settings`.

And the second problem was `/usr/bin/env: ‘node’: No such file or directory`. Fixed it by adding to the same SublimeLinter user settings file: 
 ```
   "linters": {
        "jshint": {
            "disable": false,
            "args": [],
            "excludes": [],
            "env": {
                "PATH": "~/.nvm/versions/node/v8.11.1/bin:$PATH"
            },
        },
    },
```

**Comment by trisweb** [comment]
@rreckonerr's solution fixed SublimeLinter using the wrong node version for me, which resulted in the error "SyntaxError: Use of const in strict mode." in case anyone else is encountering that. Sticking the nvm path in there works just fine.

**Comment by eriku** [comment]
Installing this fixed it for me: https://github.com/int3h/SublimeFixMacPath

**Comment by mklef121** [comment]
> Had the same problem running Linux Mint 18.3 and node installed with nvm.
> First problem I got was `SublimeLinter: WARNING: jshint cannot locate 'jshint'`. To fix it add
> 
> ```
>     "paths": {
>         "linux": [
>             "~/.nvm/versions/node/v8.11.1/bin",
>         ],
>         "osx": [],
>         "windows": []
>     },
> ```
> 
> to your `~/.config/sublime-text-3/Packages/User/SublimeLinter.sublime-settings` or `Preferences > Package Settings > SublimeLinter > Settings`.
> 
> And the second problem was `/usr/bin/env: ‘node’: No such file or directory`. Fixed it by adding to the same SublimeLinter user settings file:
> 
> ```
>   "linters": {
>        "jshint": {
>            "disable": false,
>            "args": [],
>            "excludes": [],
>            "env": {
>                "PATH": "~/.nvm/versions/node/v8.11.1/bin:$PATH"
>            },
>        },
>    },
> ```
> 
> @brainthinks Thank you for the `"PATH": "/home/user/n/bin:$PATH"`

This Worked for me.

**Comment by bebbi** [comment]
Solutions like what @mklef121 quotes seem to depend on timing in some ways. They only work intermittently for me in an nvm setup.

The one @eriku posted is the first that appeared to work consistently for me.

**Comment by iknpx** [comment]
You can setup symlink for nvm version of node to `/usr/local/bin` in your `~/.zshrc`

```bash
ln -sf /Users/iknpx/.nvm/versions/node/$(nvm current)/bin/node /usr/local/bin/node
```

**Comment by lopezdp** [comment]
> Had the same problem running Linux Mint 18.3 and node installed with nvm.
> First problem I got was `SublimeLinter: WARNING: jshint cannot locate 'jshint'`. To fix it add
> 
> ```
>     "paths": {
>         "linux": [
>             "~/.nvm/versions/node/v8.11.1/bin",
>         ],
>         "osx": [],
>         "windows": []
>     },
> ```
> 
> to your `~/.config/sublime-text-3/Packages/User/SublimeLinter.sublime-settings` or `Preferences > Package Settings > SublimeLinter > Settings`.
> 
> And the second problem was `/usr/bin/env: ‘node’: No such file or directory`. Fixed it by adding to the same SublimeLinter user settings file:
> 
> ```
>   "linters": {
>        "jshint": {
>            "disable": false,
>            "args": [],
>            "excludes": [],
>            "env": {
>                "PATH": "~/.nvm/versions/node/v8.11.1/bin:$PATH"
>            },
>        },
>    },
> ```
> 
> @brainthinks Thank you for the `"PATH": "/home/user/n/bin:$PATH"`

@rreckonerr This solution worked for me on macOS Catalina on zsh terminal and nvm. Thank you!

**Comment by nodesocket** [comment]
Also confirm the following below `env` works instead of adding nvm setup to `.zprofile`. Set the following in `SublimeLinter.sublime-setting`:

```

"jshint": {
            "@disable": false,
            "args": [],
            "excludes": [],
            "env": {
                "PATH": "/Users/justin/.nvm/versions/node/v14.20.1/bin:$PATH"
            }
        },
```

Obviously replace the username `justin` and version of node `v14.20.1` above.

**Comment by mattpr** [comment]
I know this is a super old (recurring) topic...but there aren't any solutions that allow SublimeLinter to use project-specific node versions in parallel (different node versions).  So I'll add one.

This isn't exactly sublimelinter's problem...but it is a general problem as more languages move towards project-specific interpreter/runtime versions and project-specific dependencies (python venv, nodejs .nvmrc, etc).  The linter/linter-version may be project-specific dependency rather than a global install (supports CI, common basis for teams, etc).  The project linter version may depend on a specific interpreter/runtime version (python, nodejs, etc).  A system may have many different versions of an interpreter/runtime installed and different mechanisms to activate a given version for a project (venv, nvm, etc).

There is a reasonable work-around that allows you to use multiple different node versions (via nvm) in sublime in parallel.  Only downside is that it requires using sublime-project files (open as project instead of dir) in order to have project-specific linter configs (PATHs) (ie different node versions for different projects).

Sublime/linter are not nvm-aware...they just rely on Sublime sourcing dotfiles at startup and then finding stuff on the PATH. 
So you need to look for ways to make sure your PATH is updated in the right places so that the node/npm version found first on the PATH is the one you want.

# only one node version across all of sublime (not optimal)

So sublime sources your dotfiles on startup...so it will get PATH/etc from there...to ensure that sublime (and therefore sublimelinter) can find the node version you want.

> (aside) _If your linter is completely broken (e.g. eslint not found) it is likely just a dotfile problem with overwriting PATH or not setting NVM vars correctly._

However!  The point of nvm is that you can run multiple version of node/npm in parallel.  The above means you get a single node/npm version for all of sublime-land.  Which is not a problem if you only work on a single project with a single version of node/npm at a time.

> Keep in mind that it is best to avoid using global modules and use project specific modules/dependencies/versions so that tests are predictable (for instance if you have eslint as part of acceptance test before committing to git and your production build system uses eslint 9+ and you are testing locally with eslint <9...there are a lot of differences).

If you can live with only one project (and node version) at a time, then you can use:

```bash
export NVM_SYMLINK_CURRENT=true  # creates $NVM_DIR/current/bin/ symlink pointing at latest nvm use version
nvm use    # run from your project dir.  assuming you have .nvmrc in your project dir specifying project version.
```

...and THEN start sublime (so `/current/` symlink is in place before sublime starts).  In your dotfiles you should make sure to add the symlink to the front of your path.

```bash
PATH="${NVM_DIR}/current/bin/:$PATH"
```

This will ensure that whatever the latest `nvm use` was (in any terminal) is always showing up as the current node version for all terminals/apps as default (nvm use modifies the current terminal/session's PATH and overrides this by adding another segment to the beginning of PATH).

You also need to make sure you aren't re-running nvm in your dotfiles if nvm is already initialized.  ie default nvm dotfile stuff needs to be wrapped in some check (like if `NVM_DIR` already set, don't do anything).  Reason why is that sublime sources your dotfiles at startup and so may re-write the `.nvm/current` symlink based on Sublime's own env which is likely not the same as your project/terminal env.  This may or may not work depending on the extent of NVM setup in the environment sublime inherits from the process that launches it.

If you have 2 different node projects open at the same time that each use a different node version, then just relying on single/global sublime PATH to pick the right node version won't cut it.

# multiple node (via nvm) versions in parallel in sublime

Alternatively... if you can live with opening Sublime project files instead of opening project folders (I find this annoying to remember), you can use `<project-name>.sublime-project` [files](https://www.sublimelinter.com/en/latest/settings.html) in each project in order to override the sublime PATH on a per-project basis.  Alone, this would involve hard-coding nvm version bin dir paths into your project file...which is not sharing/check-in friendly.

So I also add some preparation on the npm package side that we can then use in our sublime project file.

For instance, I've setup my `npm-init.js` to set 

- desired node version in `.nvmrc`
- `engines` node version in project `package.json` (matches nvmrc)
- `engine-strict=true` in project `.npmrc`  (so `npm install` will fail if wrong node version is in use)
- add special `prepare` script to project `package.json` (runs before lots of things like `npm install`)
    - `"prepare": "source $HOME/.nvmrc; nvm use; NODE_DIR=$(dirname $(nvm which --silent)); ln -s \"$NODE_DIR\" ./.node_dir ",`

This creates a special directory symlink `.node_dir` pointing to the current nvm bin dir (should be per .nvmrc).  Can name it what you want.

Of course you will want to add that symlink to your `.gitignore`.


...and then create a `<myproj>.sublime-project` file in the project directory like this in order to tell SublimeLinter to use a path (for this project) that includes our project-specific node symlink dir.  Of course you can also create this file via your `npm-init.js` as well so you don't have to manually create any of this.

```json
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings":
    {
        "SublimeLinter.linters.eslint.enabled": true,
        "SublimeLinter.linters.eslint.env": {
            "PATH": "${folder}/node_modules/.bin:${folder}/.node_dir/:${PATH}"
        },
    }
}
```
