### ISSUE TITLE
Plugin is generally unreliable.

### ISSUE THREAD

**Issue by jtremback** [SublimeLinter/SublimeLinter3#222]
This is the worst bug report ever, and I won't blame you for closing it, but it's true.

Much of the time, SublimeLinter does not work. The reasons seem to be varied, but it is simply not very robust.

Just now, the jshint extension did not work. I put it into debug mode and there was no console output. I fixed this by deleting the folder's .jshintrc file and then restoring it. 

The time before that, the culprit was a broken .eslintrc in a parent directory. Even though the directory that I was in had a good .eslintrc, the one above it seems to have caused the problem. This time, the debug console did print the shell command that it used to run eslint, but there was no indication of what the error might be.

Now, I agree, both of these issues were probably my fault. But comparing this plugin to something like JSHint Gutter, which seems to work no matter what you do, it's a much more frustrating experience. Might be good to have some sensible defaults or at least some better error reporting.

**Comment by skj3gg** [comment]
Either of those times, did you check that the linter itself worked from the command line?

As you probably know, SublimeLinter is a framework for simply running command line linters and searching the standard output for known values. This makes it pretty fragile between the user's setup ecosystem of software and SublimeText. JSHint Gutter, on the other hand, utilizes a builtin version of JSHint and a JS script to interact with the library directly instead of its command line output. Leaving the only obligation/fault/point-of-entry being where the user has their Node runtime. I realize it's frustrating when it fails to work, but where the blame lies is tougher to determine than a overall blanket at SL.

> But comparing [SL] to something like JSHint Gutter, which seems to work no matter what you do, it's a much more frustrating experience.

Comparing this plugin to JSHint Gutter is comparing a swiss army knife to an allen wrench. The allen wrench (JSHint Gutter and the like) does one thing very well, but the swiss army knife (SL) has to do a whole lot of things, and sometimes, it's got what you need but it falls short comparatively to that one-purpose tool. 

With that said, if the allen wrench does what you need it to, by all means use that :smile:. Let us know if you come across those problems again and what the linter's command line output says.

Thanks for the voice though!
