### ISSUE TITLE
User interface frozen on save

### ISSUE THREAD

**Issue by laserbyte** [SublimeLinter/SublimeLinter3#251]
Mac OS 10.8.5
Sublime build 3083

SublimeLinter-contrib-CFLint plugin
https://github.com/ckaznocha/SublimeLinter-contrib-CFLint

CFLint 0.2.0
https://github.com/cflint/CFLint

With the lint mode set to background every time I save a file I get the spinning beach ball for a few seconds and the user interface is frozen. Presumably the plugin is running cflint and waiting for that to return which ties up the user interface. I base this assumption on when I run CFLint from the command line it takes about the same amount of time to process the file as the interface is frozen when I save.

**Comment by skj3gg** [comment]
When you run CFLint from the command line can you do anything else, like open other windows. Background linting sends linting processes to different threads so it shouldn't be waiting on it, but AFAIK that wouldn't stop CFLint from bring your computer to a halt. The part I'm confused about is that this happens when you save and not all the time since it is `Background` linting and not `Save Only` or `Load/Save`

**Comment by laserbyte** [comment]
When I run CFLint from the command line (using iTerm) I can continue on with other tasks. If there are any other details I can provide let me know.

**Comment by braver** [comment]
@laserbyte Does this problem still occur in recent versions of Sublime Text and SL? A bunch has changed since.

**Comment by laserbyte** [comment]
So far from my testing running the latest versions of all the software I haven't had any issues.

Thanks!

**Comment by braver** [comment]
w00t!
