### ISSUE TITLE
Error when put php tag inside javascript <script> tag

### ISSUE THREAD

**Issue by nhymxu** [SublimeLinter/SublimeLinter3#254]
I have abc.php file with

```
<script type="text/javscript">
function test() {
 var a = '';
 <?php echo "b='abc';"; ?>
}
</script>
```

and get error ***syntax error*** at <?php

Why? and how to fix it?

Try disable all javscript and php plugin, enable one by one but not help
If I put <?php ?> tag outside <script></script> tag then not error notice

**Comment by jawshooah** [comment]
Which linters are you using?

Some linters use syntax scopes to lint embedded content, like JavaScript inside HTML `script` tags. The `<?php...?>` syntax is not valid JavaScript, but it is linted along with the rest of the script contents because it is inside the `source.js.embedded.html` syntax scope.

Unfortunately there's not much we can do about this, as the contents of the embedded scope are determined by the syntax definition.

Also, I don't think this is related, but you're misspelling `javascript` in your `script` tag.

**Comment by nhymxu** [comment]
try native php, phpcs, phpmd, jslint or disable all plugin :(

**Comment by skj3gg** [comment]
When you run any of those linters from the command line, what is the output?

**Comment by ATouhou** [comment]
Guys could you send me the config for enabling sublimelinter's php and js.  I have both php and nodejs installed locally -.- What is best, to use all through nodejs , or php through php executable and nodejs for rest?

**Comment by nhymxu** [comment]
This is my config. hope this help
```
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Knob/symbol/Knob - symbol.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "jsl": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "php": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "phpcs": {
                "@disable": true,
                "args": [],
                "excludes": [],
                "standard": "PSR2"
            },
            "phplint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "phpmd": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "rulesets": "cleancode,codesize,controversial,design,naming,unusedcode"
            }
        },
        "mark_style": "fill",
        "no_column_highlights_line": false,
        "passive_warnings": true,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": [
                "E:\\Software\\OpenServer\\modules\\php\\PHP-5.4\\",
                "E:\\Software\\OpenServer\\modules\\php\\PHP-5.4\\PEAR\\",
                "E:\\Software\\Dev\\jsl-0.3.0\\",
                "E:\\Software\\Dev\\phplint-2.1_20150305\\",
                "E:\\Software\\Dev\\Nodejs\\"
            ]
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

**Comment by ATouhou** [comment]
Thanks @nhymxu  That fixed the problem :D  I had         "passive_warnings": false,
and my paths did not have the "double \ "   changing those things fixed it!


Thanks alot :-) 
I just tried the "bug" you reported. 
inside html and script tags, doing
			 					var hey = 2+<? echo "2"; ?>; 
results in "6" errors.
Expected an identifier and instead saw '<'> 'echo' is not defined; Expected ':' and instead saw '2'; Expected an identifier and instead saw ';'; Expected an operator and instead saw '?'; Expected an operator and instead saw '>', Line 267, Column 49....


So basicly the linter does not accept php inside script tags. I agree that best practice is attaching the PHP value to an html object, and grabbing that with JS,  but still , the linter should not return errors on doing something acceptable (Y).



Like you the linters I use is:

            "windows": [
                "C:\\php\\",
                "C:\\php5.6\\",
                "C:\\MAMP\\bin\\php\\php5.4.1\\",
                "C:\\Program Files\\nodejs\\"
            ]

**Comment by durz** [comment]
As mentioned above, currently all `<script>` blocks in a HTML document are treated as though they are JavaScript. There are, however, very valid use cases for `<script>` blocks to *not* contain JavaScript. This is very common in libraries that support templating.

For example, when using Kendo UI, HTML templates are inserted inside of script blocks with a specific value for the `type` attribute (`text/x-kendo-tmpl`). 

````
<script type="text/x-kendo-tmpl">
    <tr data-uid="#= uid #">
        <td>...</td>
    </tr>
</script>
````

When using a linter like JSHint, there isn't an issue because JSHint itself knows how to take a HTML document and extract JS from it (using the `--extract` option) by looking for script blocks which have either a `type` attribute with a value of `"text/javascript"`, or no `type` attribute at all. This is consistent with modern browser's handling of script tags where unknown script types get ignored: https://developer.mozilla.org/en/docs/Web/HTML/Element/script#attr-type.

However, with another type of linter like eslint that takes pure JS as its input, the contents get treated as JS so, naturally, the linter reports errors like:

> Unexpected token <

The HTML5 spec for the script element does not impose limits on the value of the `type` attribute, aside from requiring it to be a valid MIME type: http://www.w3.org/TR/html5/scripting-1.html#scriptingLanguages

So, is there a way that SublimeLinter can check the script's type and then only pass the contents to a JS linter if the script block can be treated as JS?

**Comment by smwht** [comment]
+1 on this.

**Comment by grotewold** [comment]
@durz 

> So, is there a way that SublimeLinter can check the script's type and then only pass the contents to a JS linter if the script block can be treated as JS?

This could be done, and I hope it does get done, but this won't directly solve the original issue. Please make a new issue so that this doesn't get lost in the margins.

**Comment by grotewold** [comment]
Coming back to this, what @jawshooah said is right, this is out of SublimeLinter's scope (get it.... scope... man I'm funny). SL lives and dies by SublimeText's ability to determine the language scope in a document. I wish it wasn't the case, but this is some place where we are under the constraints of the editor.

I'm closing this issue, and am sorry that there isn't something more we can do.

**Comment by Alexnder** [comment]
If anyone is still interested in solution I have written eslint plugin to solve the issue: [eslint-plugin-exclude-php-tags](https://www.npmjs.com/package/eslint-plugin-exclude-php-tags)
