### ISSUE TITLE
Setting to prevent creation of "fixed" color schemes

### ISSUE THREAD

**Issue by anlutro** [SublimeLinter/SublimeLinter3#292]
I appreciate the idea behind it but for my setup it's really not necessary. I constantly have to `rm -rf` the SublimeLinter directory after merely trying other color schemes.

**Comment by grotewold** [comment]
Thanks for your input, currently SL needs to be sure the proper colors are in the color scheme so that it can use them, I'm not sure there is an easy way around this, but I'll look into an alternative. Until then there is a option in SL's menu options that clears the SL color schemes folder for you, so that you don't need to run your remove command.

**Comment by braver** [comment]
The SL4 beta provides this feature, check it out!  https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta
