### ISSUE TITLE
Auto toggle linter based on available config file

### ISSUE THREAD

**Issue by tleunen** [SublimeLinter/SublimeLinter3#339]
Would it be possible to automatically toggle the right linter based on the configuration file inside a project?

For example, I constantly have to switch betwee jshint and eslint because some projects I work on are based on jshint and some other based on eslint.

So it would be great if the plugin could detect the `.jshintrc` or `.eslintrc` file and toggle the right linter based on that.

**Comment by grotewold** [comment]
The problem with detecting based off of a `.jshintrc`, etc. is the case where even though they have one, do they want it automatically on this time? I honestly can't remember but the `.sublimelinterrc` would be a great for this, if it isn't there already. I'd check there first, but would that be a possible fix to this issue?

**Comment by tleunen** [comment]
Hmm.. Why would you want to disable the linter if you have a file inside the current project? (The detection could be done at start, so the users can anyway disable it).

Wasn't aware of this `.sublimelinterrc` file.
What setting should I use to disable all linter except the ones I specifically set?

And also, for example, if by default I configure the editor to enable ESlint and disable jshint and jscs. But then I go inside a specific project which want jscs and jshint but not eslint, based on the config file, it will enable/disable the right ones. But what if I close the project and go inside another project without any config file. Which linters will be enable?

**Comment by grotewold** [comment]
The example for the first part is someone named Jill, who follows jshint methodology but her coworker does not. The coworker may have allowed Jill to check in her .jshintrc file but since the other doesn't use it when Jill goes to into their work, 300 errors come up and she doesn't have time to fix all of those issues right now. Jill may want to disable jshint at least for now to avoid the clutter.
Additionally to that, Not all linters have a config file.

The setting to .sublimelinterrc would probably have to be added.

And you bring up possibly the best question about what is the process of reenabling linters when there is no config file. You could, instead of disabling them, suppress them, but then how do you override that.

**Comment by jawshooah** [comment]
I'm confused. What's the problem here? The [documentation](http://www.sublimelinter.com/en/latest/settings.html?highlight=sublimelinterrc#sublimelinterrc-settings) is pretty clear on how `.sublimelinterrc` works.

If you open a project with no `.sublimelinterrc` (and no `*.sublime-project` that includes SublimeLinter settings), we fall back to your global settings.

**Comment by tleunen** [comment]
In this case, that's good.

@grotewold your example is a bit weird, why the second coworker would not use the jshint file? Anyway I think that's more of a edge case.

**Comment by grotewold** [comment]
> why the second coworker would not use the jshint file?

Because they're lazy and just don't care about linting.

> I think that's more of a edge case

It may be, but it a piece of a larger idea that making decisions for the user is totally the opposite of SL3 ideals. We allow the user to define their dev env. Programmatically deciding what is on or off is not that.


All said and done, @jawshooah is right. `.sublimelinterrc` is the way to go for auto-toggling linters per project.

**Comment by tleunen** [comment]
I agree with that, adding a way to toggle linter in `.sublimelinterrc` would be great!

**Comment by grotewold** [comment]
This actually exists already, check out this example rc.

`.sublimelinterrc`
```json
{
    "linters": {
        "jshint": {
            "@disable": true
        }
    }
}
```

I believe this is closed now. Let me know if you have more questions. Thanks!

**Comment by tleunen** [comment]
Oh nice, I'll check that! Thanks

**Comment by tleunen** [comment]
Hmm.. on the website, I can see this note:
> A meta setting at the global level overrides the same linter meta setting. For example, even if "@disable" is true within a linter’s settings, setting "@disable" to false at the global level will override the linter setting and enable that linter.
Does it mean my user setting will always override the project setting?

**Comment by grotewold** [comment]
This is not the case with the runtime configs. my Sublimelinter setting for `@disable` jshint is `true` but my `.sublimelinterrc` is `@disabled: false`... jshint works. Switching both, jshint does not work. `.sublimelinterrc` takes precedence over `Sublimelinter.sublime-settings`

**Comment by tleunen** [comment]
Hmm.. I can't make it work.
I have a file with this:
```{
    "linters": {
        "eslint": {
            "@disable": true
        },
        "jshint": {
            "@disable": false
        }
    }
}
```
So I want jshint to be enabled, but not eslint. (which is the opposite of my global settings), but inside my project, the settings which are used are the global settings, not the ones from the rc file.

**Comment by grotewold** [comment]
What's your `rc_search_limit` setting set to? and then how far is your file from the rc file? might try upping your `rc_search_limit`.

**Comment by tleunen** [comment]
The file is at the root and I checked files at the root and files under sub-directories as well. Same thing :/
The limit is set at 3 by default, which I'll probably set to 0.

**Comment by tleunen** [comment]
Yep nvm.. Seems like it's working but I was still checking the "toggle linter" menu, which displays the global settings.

**Comment by grotewold** [comment]
Yes, that is an “issue” I am noticing. New problem arises when it fixed though. What gets toggled when you try to toggle one then? Arguably it’s the one active, so the `.sublimelinterrc` would change. BUUUT… that causes the issue of the .sublimelinterrc file being changed too much, which could clutter git commits if user isn’t paying attention.




Thoughts? Maybe it’s best to just document this and let it be?

**Comment by tleunen** [comment]
The menu is bound to the user settings, so if you change it, it will only change the user settings.

In this case, I think for now it's ok to let as is. But in an ideal world, it would be great if the menu could display the current applied settings. (And maybe put the user settings in parentheses so both info would be available)

**Comment by grotewold** [comment]
Agreed, thanks!
