### ISSUE TITLE
Theme settings are broken.

### ISSUE THREAD

**Issue by atilkan** [SublimeLinter/SublimeLinter3#409]
What is this line of code in my settings? I think you overwrote something. 

`"color_scheme": "Packages/User/SublimeLinter/Monokai (SL).tmTheme",`

**Comment by groteworld** [comment]
You are correct, check out these docs for information about it. http://www.sublimelinter.com/en/latest/usage.html?highlight=color%20scheme#choosing-color-schemes

**Comment by atilkan** [comment]
There is still problem. It messes up my current theme.

**Comment by groteworld** [comment]
Alright, can I see a screenshot? How is it messing it up?

**Comment by atilkan** [comment]
Resets my theme to default theme. I believe the idea is taking current theme and adding colors to it. It doesn't do that. When and update comes, i will upload a screenshot.

**Comment by Krinkle** [comment]
I ran into a similar issue. After installing SublimeLinter on a fresh Sublime Text 3 install, I got various warnings about `SublimeLinter/Monokai Bright (SL).tmTheme` not existing. This fixed itself after switching to another color scheme and back again.

I believe in my case I caused it myself by setting this value directly in the Sublime preferences right after installing the SublimeLinter plugin. This happened because I have the Sublime preferences symlinked from a Git repo and I only just installed the SublimeLinter plugin a minute before on this machine. Restarting Sublime first or switching color scheme fixed it for me and now works fine.

**Comment by braver** [comment]
No indication anything is wrong here

**Comment by MichaelPoP** [comment]
![Screen Shot 2019-03-22 at 4 09 07 PM](https://user-images.githubusercontent.com/8924827/54857542-284a5200-4cbd-11e9-94c7-3490eb18de82.png)
I am literally unable to use sublime editor after updating

**Comment by Krinkle** [comment]
@MichaelPoP Those better not be production tokens for WordPay.

**Comment by MichaelPoP** [comment]
Nothing there was production but good looking out. Probably should not put
screenshots of anything from my work computer.
