### ISSUE TITLE
Implement phantoms for lint errors

### ISSUE THREAD

**Issue by iamntz** [SublimeLinter/SublimeLinter3#470]
Would be super nice to get an option to display error via phantoms, something similar to this:

https://forum.sublimetext.com/t/dev-build-3118/21270/33

![](http://i.imgur.com/MsjH9qj.png)

**Comment by rchl** [comment]
I've added such hack in my local copy and been using it for a while. One thing that would have to be thought out is how to handle cases like 

// TODO(me): Do something

This is highlighted in the gutter right now but if using phantoms, it should not show up for this case because then it would just duplicate the text of the TODO. So either that should be customizable per plugin or plugin should specify that. Also one plugin might want to show phantom for some errors and not for other.

**Comment by Arkkimaagi** [comment]
@rchl could you please share your hack?

**Comment by rchl** [comment]
Sorry but I've stopped using it and I can't find the code anymore in my local repo.

It was annoying because phantoms were re-created every time the file was changed. That make the whole text content jump a lot if there were many issues in the file.

It needs more thought on how to do it properly and probably the phantom markers would have to bve cached so that they don't constantly appear and disappear. Would probably make sense to gray them out when linter thinks they might not be relevant anymore rather than removing them instantly.

**Comment by braver** [comment]
> It was annoying because phantoms were re-created every time the file was changed

Yeah, this really makes phantoms a bad fit. You could set up your linter as a build system and run it on demand like this. If setup well you'll get phantoms kind of as a todo list. This workflow is a bad fit for SublimeLinter so we're not going to use phantoms as a feedback mechanism, but it's also easily achieved without using any plugins.

**Comment by slifin** [comment]
@braver Are you saying it's possible to create a build for lint tools (to get phantoms)? How does sublime know where to place the phantoms? 
I'm asking because I find these phantoms useful at code review so reviewees have nice visual feedback, I've been trying to use this plugin https://github.com/alexkuz/SublimeLinter-inline-errors but it runs terribly

**Comment by braver** [comment]
Most linters run a utility in the background, and we pass the output of that utility to get line number, column, and message for each error. SublimeLinter is basically a plugin that allows running these utilities on the fly and on unsaved files. SublimeText build systems allow you to do something similar but on demand. Read more here: https://www.sublimetext.com/docs/3/build_systems.html. If you want help setting up build systems you can ask around on the forums.
