### ISSUE TITLE
WARNING: no htmllint version could be extracted from: <blank>

### ISSUE THREAD

**Issue by BartBurger** [SublimeLinter/SublimeLinter3#509]
When I open any html file, I see this in the console:
`SublimeLinter: WARNING: no htmllint version could be extracted from:
local .htmllintrc file not found (you can create one using "htmllint init")`
Linting doesn't work (nothing happens)

OS: Windows 7
npm 3.7.3
node 6.8.1
htmllint 0.0.5

When I run htmllint from the command line, it works fine.
Sublime can't find the plugin apparently. It's in my PATH.
I've also tried `where htmllint` and added that path so the paths config of SublimeLinter.
Hopefully someone can tell me what I am doing wrong here.

Thanks in advance!

**Comment by SecureCloud-biz** [comment]
Since no-one seems to respond, I had the same ```WARNING``` now I dont..

STEPS (that worked for me)..
      [make sure you already ran..  ```npm install -g htmllint-cli```  ]
```
    open CMD prompt OR .. Start => (type) CMD
    type: cd\
      [You should be at the root now  C:\ ]
    type: htmllint init
```

Basically that creates the file for you in your root ```C:\.htmllintrc```
open Explorer, navigate in left column to  ```C:\```
you should see file in right side column.
**COPY IT**

Then i copied a version into EACH folder of the ```htmllint-cli``` folders listed below
mine was located at:
```
    C:\Users\ **YourUserName** \AppData\Roaming\npm\node_modules\htmllint-cli
    C:\Users\ **YourUserName** \AppData\Roaming\npm\node_modules\htmllint-cli\bin
    C:\Users\ **YourUserName** \AppData\Roaming\npm\node_modules\htmllint-cli\lib
```

I pasted one in the root ```htmllint-cli``` folder
also inside ```lib``` and ```bin```

and just to be safe.. (lol)
I pasted a copy in (2) folders of my Sublime Program folder below
mine is located at:
```
    C:\_______Sublime_Text_x64\
    C:\_______Sublime_Text_x64\Data\Installed Packages
```

Hope this helps..
Like I said, this worked for me.. I am still not exactly sure **WHICH** one got rid of error
but its gone now.. Good Luck :+1:

**Comment by braver** [comment]
Jup, basically your linter needs a configuration to work and it probably has some rules for how it's going about finding it (usually walking all the way up from a file's location and including your home dir). Making sure it'll be able to find that file is the key to success here.
