### ISSUE TITLE
Improve interaction with tooltips (popups)

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter3#619]
- tooltips follow the cursor, which is super annoying
- they don't disappear when the lint-issue is resolved
- when you move the mouse the tooltip disappears for some reason
- but hovering over an error-region doesn't open the popup (which would be so much more useful than on_selection_change)
- ~~when the popup disappears it hides all popups, making it fight with plugins like GitGutter~~
- ~~for some unclear reason it displays the line number (it is *at the line*!) but it's off by one~~

Also, there are 2 themes with no apparent advantage of one over the other. You can configure the font-size via a setting, but if the template would [follow the new guidelines](https://www.sublimetext.com/docs/3/minihtml.html#best_practices) there would be no need for that. 

Suggestions:

- hover over the gutter to display all errors for that line
- hover over an error range to display that specific error
- remove templates and create 1 very simple tooltip

This supersedes issues: #568, #565, #564, #560

#471 has some more info about making the tooltips open on_hover instead of on_selection_change

PR #579 will fix some of this, as will #617, however I don't think fixing this issues by issue is going to work. Some of the code is probably salvageable, but overall tooltips need to be completely re-implemented for the new stable 3.0 api.

Edit: updated because since recent events it's not so bad anymore

**Comment by Cerberus-tm** [comment]
I mostly agree with the suggested changes. What made me turn off tooltips is that they activate when you click on the line (but outside the error area), and when you are still typing when you pause to think or look at your code. That tends to obscure my view of the line I'm typing and the one above/below. And it makes e.g. autocomplete disappear, when the tooltip appears as you're typing.

Instead of 'on hover', I'd prefer for the tooltip to appear when you **click** on the error (the code inside the red or yellow rectangle); and for all tooltips of the line to appear when you click on the error symbol in the margin.

**Comment by dsl101** [comment]
Sorry if this isn't the right place—I got a bit lost in the thread of related issues. I've recently added this flag at line 469:
```
active_view.show_popup(tooltip_content,
   flags=sublime.HIDE_ON_MOUSE_MOVE_AWAY | sublime.COOPERATE_WITH_AUTO_COMPLETE,
   location=-1,
   max_width=600)
```
Works much better now when linting picks up a half-finished bit of typing, and then won't go away. I really wish there was HIDE_ON_TYPING—that would solve it for me :).

**Comment by dsl101** [comment]
So,, you don't like that extra flag?

**Comment by braver** [comment]
Oh, aha, wasn't clear. We've completely redone tooltips in SL4 (#666), so there shouldn't be a need for that flag. You can try it if you like: https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta

**Comment by dsl101** [comment]
Ah, great. Thanks for the link. I will definitely try it :)
