### ISSUE TITLE
Config 'syntax_map' not working as expected

### ISSUE THREAD

**Issue by JoeMShanahan** [SublimeLinter/SublimeLinter3#695]
I am attempted to map the syntax "Yeod Julius" to "JavaScript" so that `jshlint` will work on my `.julius` files.

I am using the package https://packagecontrol.io/packages/Yesod which sets the syntax to "Yesod Julius":

![image](https://user-images.githubusercontent.com/29176664/33844213-8364441a-de97-11e7-8c7a-ce2ef1d04e4f.png)

I would have expected the config

    "syntax_map": {
        "yesod julius": "javascript",
    }

to result in my file now being ran against `jshint`, but it is not. If I change the syntax to "JavaScript" I get the hints as expected.

**Comment by braver** [comment]
It’s a mapping based on file name (don’t as me why). Can you try it with a dash in between yesod and julius?

**Comment by FichteFoll** [comment]
It's a lot easier to base it on the file name since you don't have to parse the file in order to determine its display name.

You can fetch the name to use with this console line: 

```py
import os.path; os.path.splitext(os.path.basename(view.settings().get('syntax')))[0]
```

**Comment by braver** [comment]
> It's a lot easier to base it on the file name since you don't have to parse the file in order to determine its display name.

Sure, but it doesn’t explain how users are supposed to find out what to put in the mapping. Must be a design choice from way back when. 🤷🏼‍♂️

This seems resolved to me.

**Comment by FichteFoll** [comment]
Just a note that ideally this will be prevented by https://github.com/SublimeLinter/SublimeLinter3/issues/691, although the syntax in question uses `source.yesod.julius` instead of `source.js.yesod.julius`.

Since it looks like a templating language, it should be using the new `.sublime-syntax` format and `with_prototype` anyway. It's probably not going to be updated. We should consider cases where you'd need to adjust to weird base scope names of third-party syntaxes in #691.
